spring:
  application:
    name: apollo
  profiles:
    active: dev
  devtools:
    livereload:
      port: 35734
  thymeleaf:
    checkTemplateLocation: false
server:
  port: 8084

# apollo配置
app:
  id: apollo
apollo:
  meta: http://192.168.31.29:8080
  #  meta: 10.30.16.4:10002
  bootstrap:
    enabled: true
    # application表示当前应用，也可以使用其他的公共namespace
    namespaces: application,resource
    eagerLoad:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
