spring:
  application:
    name: admin-client2
  profiles:
    active: qa
  devtools:
    livereload:
      port: 35732
  thymeleaf:
    checkTemplateLocation: false
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
