#######################
# spring相关的配置
#######################
spring:
  boot:
    admin:
      client:
        url: http://localhost:8082
        username: admin
        password: 123456
        instance:
          name: xxl-job
          #client访问地址
          service-base-url: http://localhost:${server.port}

xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8089/xxl-job-admin
    executor:
      appname: springboot-jobtask
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 3
      port: 10044
xxl-job:
  executor:
    enable: true